apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service2.name }}
  labels:
    {{- include "lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.targetPort }}
      protocol: {{ .Values.service2.protocol }}
  selector:
    app: {{ .Values.deployment2.name }}
