apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service1.name }}
  labels:
    {{- include "lab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service1.type }}
  ports:
    - port: {{ .Values.service1.port }}
      targetPort: {{ .Values.service1.targetPort }}
  selector:
    app: {{ .Values.deployment1.name }}